"""Semantic vector memory helpers for the Signo AI backend.

PostgreSQL stores structured memory: exact fields like driver_id, phone_number,
payment status, and call_log_id.

Pinecone stores semantic memory: vector embeddings that help the AI find old
calls by meaning, even when the new query uses different words.

This version uses local embeddings from sentence-transformers instead of
OpenAI embeddings. Local embeddings run on this machine, so there are no
OpenAI API calls and no OpenAI embedding billing.
"""

import os
import time
from datetime import datetime, timezone
from uuid import uuid4

from dotenv import load_dotenv


load_dotenv()


EMBEDDING_MODEL = "all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384
PINECONE_METRIC = "cosine"
_embedding_model = None


def _get_local_embedding_model():
    """Load and reuse the local sentence-transformers embedding model.

    OpenAI embeddings are generated by an external API and may cost money.
    Local embeddings are generated by a model running on your own computer.
    The first load can take a little time, but after that the same model object
    is reused for every embedding.
    """

    global _embedding_model

    if _embedding_model is None:
        print("Loading local embedding model...")

        from sentence_transformers import SentenceTransformer

        _embedding_model = SentenceTransformer(EMBEDDING_MODEL)

    return _embedding_model


def _get_pinecone_client():
    """Create a Pinecone client only when semantic memory is used."""

    from pinecone import Pinecone

    api_key = os.getenv("PINECONE_API_KEY")

    if not api_key or api_key == "your_pinecone_api_key":
        raise ValueError("PINECONE_API_KEY is missing or still set to the placeholder.")

    return Pinecone(api_key=api_key)


def _get_index_name():
    """Read the Pinecone index name from .env."""

    return os.getenv("PINECONE_INDEX", "signo-memory")


def _get_or_create_index():
    """Return the Pinecone index, creating it first if it does not exist."""

    pinecone_client = _get_pinecone_client()
    index_name = _get_index_name()
    index_list = pinecone_client.list_indexes()

    if hasattr(index_list, "names"):
        existing_indexes = index_list.names()
    else:
        existing_indexes = [
            index.get("name") if isinstance(index, dict) else index.name
            for index in index_list
        ]

    if index_name not in existing_indexes:
        from pinecone import ServerlessSpec

        print(f"Creating Pinecone index: {index_name}")

        # all-MiniLM-L6-v2 returns 384-number vectors.
        # Pinecone must know that dimension before it can store them.
        pinecone_client.create_index(
            name=index_name,
            dimension=EMBEDDING_DIMENSION,
            metric=PINECONE_METRIC,
            spec=ServerlessSpec(
                cloud=os.getenv("PINECONE_CLOUD", "aws"),
                region=os.getenv("PINECONE_REGION", "us-east-1"),
            ),
        )

        for _ in range(30):
            description = pinecone_client.describe_index(index_name)
            status = (
                description.get("status", {})
                if isinstance(description, dict)
                else description.status
            )
            is_ready = status.get("ready") if isinstance(status, dict) else status.ready

            if is_ready:
                break

            time.sleep(2)

    description = pinecone_client.describe_index(index_name)
    index_dimension = (
        description.get("dimension")
        if isinstance(description, dict)
        else description.dimension
    )

    if index_dimension != EMBEDDING_DIMENSION:
        raise ValueError(
            f"Pinecone index '{index_name}' has dimension {index_dimension}, "
            f"but {EMBEDDING_MODEL} creates {EMBEDDING_DIMENSION}-dimension "
            "vectors. Create a new index or delete/recreate the old one with "
            "dimension 384."
        )

    return pinecone_client.Index(index_name)


def get_embedding(text):
    """Convert text into an embedding vector using a free local model.

    An embedding is a list of numbers that represents the meaning of text.
    Similar sentences usually produce vectors that are close together.

    OpenAI embeddings are created by calling OpenAI's servers. This project now
    uses sentence-transformers locally, so embedding generation does not need an
    OpenAI API key and does not create OpenAI billing.
    """

    try:
        print("Generating local embedding...")

        if not text or not text.strip():
            raise ValueError("Text is required to generate an embedding.")

        embedding_model = _get_local_embedding_model()
        embedding = embedding_model.encode(text).tolist()

        print(f"Embedding length: {len(embedding)}")

        return embedding

    except Exception as error:
        print(f"Error generating local embedding: {error}")
        return None


def save_memory(phone_number, text, metadata):
    """Save one semantic memory in Pinecone.

    PostgreSQL is best for exact lookups, such as "get this driver's latest
    payment row." Pinecone is best for meaning-based lookup, such as finding an
    older payment complaint when the driver says "my payment problem happened
    again."
    """

    try:
        print("Saving vector memory...")

        embedding = get_embedding(text)

        if embedding is None:
            return None

        index = _get_or_create_index()
        metadata = metadata or {}
        safe_metadata = {
            "phone_number": phone_number,
            "driver_id": metadata.get("driver_id", ""),
            "issue_category": metadata.get("issue_category", ""),
            "sentiment": metadata.get("sentiment", ""),
            "important": bool(metadata.get("important", False)),
            "timestamp": metadata.get("timestamp")
            or datetime.now(timezone.utc).isoformat(),
        }

        vector_id = f"{phone_number}:{uuid4()}"

        index.upsert(
            vectors=[
                {
                    "id": vector_id,
                    "values": embedding,
                    "metadata": safe_metadata,
                }
            ]
        )

        return {
            "id": vector_id,
            "metadata": safe_metadata,
        }

    except Exception as error:
        print(f"Error saving vector memory: {error}")
        return None


def search_memories(phone_number, query):
    """Search Pinecone for memories that are semantically similar to a query.

    Vector search compares meaning, not just exact keywords. That means a query
    like "payment problem happened again" can match a previous note such as
    "Driver complained about delayed payment last week."
    """

    try:
        print("Searching semantic memories...")

        query_embedding = get_embedding(query)

        if query_embedding is None:
            return []

        index = _get_or_create_index()
        response = index.query(
            vector=query_embedding,
            top_k=5,
            include_metadata=True,
            filter={"phone_number": {"$eq": phone_number}},
        )

        semantic_matches = []

        matches = response.get("matches", []) if isinstance(response, dict) else response.matches

        for match in matches:
            match_id = match.get("id") if isinstance(match, dict) else match.id
            match_score = match.get("score") if isinstance(match, dict) else match.score
            match_metadata = (
                match.get("metadata", {})
                if isinstance(match, dict)
                else match.metadata or {}
            )

            semantic_matches.append(
                {
                    "id": match_id,
                    "score": match_score,
                    "metadata": match_metadata,
                }
            )

        return semantic_matches

    except Exception as error:
        print(f"Error searching semantic memories: {error}")
        return []
