"""Semantic vector memory helpers - WITH EXTENSIVE DEBUG LOGS.

PostgreSQL stores structured memory: exact fields like driver_id, phone_number,
payment status, and call_log_id.

Pinecone stores semantic memory: vector embeddings that help the AI find old
calls by meaning, even when the new query uses different words.

This version uses local embeddings from sentence-transformers instead of
OpenAI embeddings. Local embeddings run on this machine, so there are no
OpenAI API calls and no OpenAI embedding billing.
"""

import os
import time
import traceback
from datetime import datetime, timezone
from uuid import uuid4

from dotenv import load_dotenv


load_dotenv()


EMBEDDING_MODEL = "all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384
PINECONE_METRIC = "cosine"
_embedding_model = None


def _get_local_embedding_model():
    """Load and reuse the local sentence-transformers embedding model.

    OpenAI embeddings are generated by an external API and may cost money.
    Local embeddings are generated by a model running on your own computer.
    The first load can take a little time, but after that the same model object
    is reused for every embedding.
    """

    global _embedding_model

    if _embedding_model is None:
        print("\n" + "="*80)
        print("[DEBUG-EMBEDDING] Loading local embedding model...")
        print(f"[DEBUG-EMBEDDING] Model name: {EMBEDDING_MODEL}")
        print(f"[DEBUG-EMBEDDING] Expected output dimension: {EMBEDDING_DIMENSION}")
        print("="*80)

        try:
            from sentence_transformers import SentenceTransformer

            print("[DEBUG-EMBEDDING] ✓ sentence_transformers imported successfully")

            _embedding_model = SentenceTransformer(EMBEDDING_MODEL)

            print("[DEBUG-EMBEDDING] ✓ Model loaded successfully")
            print(f"[DEBUG-EMBEDDING] Model type: {type(_embedding_model)}")
            print("[DEBUG-EMBEDDING] Ready to generate embeddings")
            print("="*80 + "\n")

        except Exception as e:
            print("[DEBUG-EMBEDDING] ❌ FAILED TO LOAD MODEL")
            print(f"[DEBUG-EMBEDDING] Exception type: {type(e).__name__}")
            print(f"[DEBUG-EMBEDDING] Exception: {str(e)}")
            print("[DEBUG-EMBEDDING] Traceback:")
            traceback.print_exc()
            print("="*80)
            print("[DEBUG-EMBEDDING] ⚠️ POSSIBLE CAUSES:")
            print("[DEBUG-EMBEDDING]   1. sentence-transformers not installed")
            print("[DEBUG-EMBEDDING]   2. Model download failed (network/permissions)")
            print("[DEBUG-EMBEDDING]   3. Insufficient disk space")
            print("[DEBUG-EMBEDDING]   4. PyTorch installation issue")
            print("="*80 + "\n")
            raise

    return _embedding_model


def _get_pinecone_client():
    """Create a Pinecone client only when semantic memory is used."""

    print("\n" + "="*80)
    print("[DEBUG-PINECONE-CLIENT] Initializing Pinecone client...")
    print("="*80)

    try:
        # Check environment variables
        api_key = os.getenv("PINECONE_API_KEY")
        pinecone_index = os.getenv("PINECONE_INDEX", "signo-memory")
        pinecone_region = os.getenv("PINECONE_REGION", "us-east-1")
        pinecone_cloud = os.getenv("PINECONE_CLOUD", "aws")

        print(f"[DEBUG-PINECONE-CLIENT] PINECONE_API_KEY exists: {bool(api_key)}")
        if api_key:
            print(f"[DEBUG-PINECONE-CLIENT] PINECONE_API_KEY length: {len(api_key)}")
            print(f"[DEBUG-PINECONE-CLIENT] PINECONE_API_KEY first 5 chars: {api_key[:5]}...")
            print(f"[DEBUG-PINECONE-CLIENT] PINECONE_API_KEY last 5 chars: ...{api_key[-5:]}")
        else:
            print("[DEBUG-PINECONE-CLIENT] ⚠️ PINECONE_API_KEY is missing!")

        print(f"[DEBUG-PINECONE-CLIENT] PINECONE_INDEX value: '{pinecone_index}'")
        print(f"[DEBUG-PINECONE-CLIENT] PINECONE_REGION value: '{pinecone_region}'")
        print(f"[DEBUG-PINECONE-CLIENT] PINECONE_CLOUD value: '{pinecone_cloud}'")

        # Validate API key
        if not api_key or api_key == "your_pinecone_api_key":
            error_msg = "PINECONE_API_KEY is missing or still set to the placeholder."
            print(f"[DEBUG-PINECONE-CLIENT] ❌ VALIDATION FAILED: {error_msg}")
            raise ValueError(error_msg)

        print("[DEBUG-PINECONE-CLIENT] ✓ API key validation passed")

        # Import and create client
        from pinecone import Pinecone

        print("[DEBUG-PINECONE-CLIENT] ✓ Pinecone SDK imported successfully")

        pinecone_client = Pinecone(api_key=api_key)

        print("[DEBUG-PINECONE-CLIENT] ✓ Pinecone client created successfully")
        print(f"[DEBUG-PINECONE-CLIENT] Client type: {type(pinecone_client)}")
        print("="*80 + "\n")

        return pinecone_client

    except Exception as error:
        print(f"[DEBUG-PINECONE-CLIENT] ❌ EXCEPTION")
        print(f"[DEBUG-PINECONE-CLIENT] Exception type: {type(error).__name__}")
        print(f"[DEBUG-PINECONE-CLIENT] Exception message: {str(error)}")
        print("[DEBUG-PINECONE-CLIENT] Traceback:")
        traceback.print_exc()
        print("="*80)
        print("[DEBUG-PINECONE-CLIENT] ⚠️ POSSIBLE CAUSES:")
        print("[DEBUG-PINECONE-CLIENT]   1. Environment variables not loaded (Render .env)")
        print("[DEBUG-PINECONE-CLIENT]   2. Network connectivity to Pinecone unavailable")
        print("[DEBUG-PINECONE-CLIENT]   3. Pinecone API key invalid or expired")
        print("[DEBUG-PINECONE-CLIENT]   4. Pinecone SDK version incompatibility")
        print("="*80 + "\n")
        raise


def _get_index_name():
    """Read the Pinecone index name from .env."""

    index_name = os.getenv("PINECONE_INDEX", "signo-memory")
    print(f"[DEBUG-INDEX] Index name from env: '{index_name}'")
    return index_name


def _get_or_create_index():
    """Return the Pinecone index, creating it first if it does not exist."""

    print("\n" + "="*80)
    print("[DEBUG-INDEX] Entering _get_or_create_index()")
    print("="*80)

    try:
        # Get Pinecone client
        print("[DEBUG-INDEX] Step 1: Getting Pinecone client...")
        pinecone_client = _get_pinecone_client()
        print("[DEBUG-INDEX] ✓ Pinecone client obtained")

        # Get index name
        print("[DEBUG-INDEX] Step 2: Getting index name...")
        index_name = _get_index_name()
        print(f"[DEBUG-INDEX] ✓ Index name: '{index_name}'")

        # List existing indexes
        print("[DEBUG-INDEX] Step 3: Listing existing indexes...")
        index_list = pinecone_client.list_indexes()
        print(f"[DEBUG-INDEX] Raw index_list type: {type(index_list)}")
        print(f"[DEBUG-INDEX] Raw index_list: {index_list}")

        if hasattr(index_list, "names"):
            existing_indexes = index_list.names()
            print(f"[DEBUG-INDEX] ✓ Extracted indexes using .names() method")
        else:
            existing_indexes = [
                index.get("name") if isinstance(index, dict) else index.name
                for index in index_list
            ]
            print(f"[DEBUG-INDEX] ✓ Extracted indexes using iteration")

        print(f"[DEBUG-INDEX] Existing indexes: {existing_indexes}")

        # Check if index exists
        if index_name not in existing_indexes:
            print(f"[DEBUG-INDEX] ⚠️ Index '{index_name}' does NOT exist")
            print("[DEBUG-INDEX] Step 4: Creating new Pinecone index...")

            try:
                from pinecone import ServerlessSpec

                print(f"[DEBUG-INDEX] Creating index with:")
                print(f"[DEBUG-INDEX]   - name: {index_name}")
                print(f"[DEBUG-INDEX]   - dimension: {EMBEDDING_DIMENSION}")
                print(f"[DEBUG-INDEX]   - metric: {PINECONE_METRIC}")
                print(f"[DEBUG-INDEX]   - cloud: {os.getenv('PINECONE_CLOUD', 'aws')}")
                print(f"[DEBUG-INDEX]   - region: {os.getenv('PINECONE_REGION', 'us-east-1')}")

                pinecone_client.create_index(
                    name=index_name,
                    dimension=EMBEDDING_DIMENSION,
                    metric=PINECONE_METRIC,
                    spec=ServerlessSpec(
                        cloud=os.getenv("PINECONE_CLOUD", "aws"),
                        region=os.getenv("PINECONE_REGION", "us-east-1"),
                    ),
                )

                print("[DEBUG-INDEX] ✓ Create index command submitted")

                # Wait for index to be ready
                print("[DEBUG-INDEX] Waiting for index to be ready (up to 60 seconds)...")
                for attempt in range(30):
                    print(f"[DEBUG-INDEX] Checking readiness (attempt {attempt + 1}/30)...")

                    description = pinecone_client.describe_index(index_name)
                    print(f"[DEBUG-INDEX]   Raw description type: {type(description)}")

                    status = (
                        description.get("status", {})
                        if isinstance(description, dict)
                        else description.status
                    )
                    is_ready = status.get("ready") if isinstance(status, dict) else status.ready

                    print(f"[DEBUG-INDEX]   Status: {status}")
                    print(f"[DEBUG-INDEX]   Is ready: {is_ready}")

                    if is_ready:
                        print("[DEBUG-INDEX] ✓ Index is ready!")
                        break

                    time.sleep(2)

            except Exception as create_error:
                print("[DEBUG-INDEX] ❌ EXCEPTION CREATING INDEX")
                print(f"[DEBUG-INDEX] Exception type: {type(create_error).__name__}")
                print(f"[DEBUG-INDEX] Exception message: {str(create_error)}")
                traceback.print_exc()
                raise

        else:
            print(f"[DEBUG-INDEX] ✓ Index '{index_name}' already exists")

        # Get index description and verify dimension
        print("[DEBUG-INDEX] Step 5: Verifying index configuration...")
        description = pinecone_client.describe_index(index_name)
        print(f"[DEBUG-INDEX] Index description type: {type(description)}")

        index_dimension = (
            description.get("dimension")
            if isinstance(description, dict)
            else description.dimension
        )

        print(f"[DEBUG-INDEX] Extracted index dimension: {index_dimension}")
        print(f"[DEBUG-INDEX] Expected dimension: {EMBEDDING_DIMENSION}")
        print(f"[DEBUG-INDEX] Model: {EMBEDDING_MODEL}")

        if index_dimension != EMBEDDING_DIMENSION:
            error_msg = (
                f"DIMENSION MISMATCH!\n"
                f"Expected: {EMBEDDING_DIMENSION}\n"
                f"Found: {index_dimension}\n"
                f"Pinecone index '{index_name}' has dimension {index_dimension}, "
                f"but {EMBEDDING_MODEL} creates {EMBEDDING_DIMENSION}-dimension "
                "vectors. You must delete and recreate the index with dimension 384."
            )
            print(f"[DEBUG-INDEX] ❌ {error_msg}")
            raise ValueError(error_msg)

        print("[DEBUG-INDEX] ✓ Dimension validation passed")

        # Get index status
        index_status = (
            description.get("status", {})
            if isinstance(description, dict)
            else description.status
        )
        is_ready = index_status.get("ready") if isinstance(index_status, dict) else index_status.ready
        print(f"[DEBUG-INDEX] Index ready status: {is_ready}")

        # Return index object
        print(f"[DEBUG-INDEX] ✓ Getting index object: {index_name}")
        index = pinecone_client.Index(index_name)
        print(f"[DEBUG-INDEX] ✓ Index object type: {type(index)}")
        print("="*80 + "\n")

        return index

    except Exception as error:
        print(f"[DEBUG-INDEX] ❌ EXCEPTION IN _get_or_create_index()")
        print(f"[DEBUG-INDEX] Exception type: {type(error).__name__}")
        print(f"[DEBUG-INDEX] Exception message: {str(error)}")
        print("[DEBUG-INDEX] Traceback:")
        traceback.print_exc()
        print("="*80)
        print("[DEBUG-INDEX] ⚠️ POSSIBLE CAUSES:")
        print("[DEBUG-INDEX]   1. Pinecone API key invalid")
        print("[DEBUG-INDEX]   2. Insufficient permissions to create indexes")
        print("[DEBUG-INDEX]   3. Network connectivity issue")
        print("[DEBUG-INDEX]   4. Pinecone account quota exceeded")
        print("[DEBUG-INDEX]   5. Index already exists with different dimension")
        print("="*80 + "\n")
        raise


def get_embedding(text):
    """Convert text into an embedding vector using a free local model.

    An embedding is a list of numbers that represents the meaning of text.
    Similar sentences usually produce vectors that are close together.
    """

    print("\n" + "="*80)
    print("[DEBUG-EMBEDDING] Generating embedding...")
    print("="*80)

    try:
        # Validate input
        print(f"[DEBUG-EMBEDDING] Input text type: {type(text)}")
        print(f"[DEBUG-EMBEDDING] Input text length: {len(text) if text else 'N/A'}")

        if not text or not text.strip():
            error_msg = "Text is required to generate an embedding (empty or None)."
            print(f"[DEBUG-EMBEDDING] ❌ {error_msg}")
            raise ValueError(error_msg)

        print(f"[DEBUG-EMBEDDING] ✓ Text validation passed")
        print(f"[DEBUG-EMBEDDING] Text first 100 chars: {text[:100]}")
        print(f"[DEBUG-EMBEDDING] Text last 100 chars: {text[-100:]}")

        # Load model
        print("[DEBUG-EMBEDDING] Getting embedding model...")
        embedding_model = _get_local_embedding_model()
        print(f"[DEBUG-EMBEDDING] ✓ Model obtained (type: {type(embedding_model)})")

        # Generate embedding
        print("[DEBUG-EMBEDDING] Calling model.encode()...")
        embedding_array = embedding_model.encode(text)
        print(f"[DEBUG-EMBEDDING] ✓ encode() returned (type: {type(embedding_array)})")
        print(f"[DEBUG-EMBEDDING] Array shape: {embedding_array.shape}")

        # Convert to list
        print("[DEBUG-EMBEDDING] Converting to list...")
        embedding = embedding_array.tolist()
        print(f"[DEBUG-EMBEDDING] ✓ Converted to list")

        # Validate embedding
        print(f"[DEBUG-EMBEDDING] Embedding length: {len(embedding)}")
        print(f"[DEBUG-EMBEDDING] Expected length: {EMBEDDING_DIMENSION}")
        print(f"[DEBUG-EMBEDDING] Embedding first 5 values: {embedding[:5]}")
        print(f"[DEBUG-EMBEDDING] Embedding last 5 values: {embedding[-5:]}")
        print(f"[DEBUG-EMBEDDING] Embedding min value: {min(embedding)}")
        print(f"[DEBUG-EMBEDDING] Embedding max value: {max(embedding)}")

        if len(embedding) != EMBEDDING_DIMENSION:
            error_msg = f"Embedding dimension mismatch! Expected: {EMBEDDING_DIMENSION}, Got: {len(embedding)}"
            print(f"[DEBUG-EMBEDDING] ❌ {error_msg}")
            raise ValueError(error_msg)

        print("[DEBUG-EMBEDDING] ✓ Embedding validation passed")
        print("="*80 + "\n")

        return embedding

    except Exception as error:
        print(f"[DEBUG-EMBEDDING] ❌ EXCEPTION IN get_embedding()")
        print(f"[DEBUG-EMBEDDING] Exception type: {type(error).__name__}")
        print(f"[DEBUG-EMBEDDING] Exception message: {str(error)}")
        print("[DEBUG-EMBEDDING] Traceback:")
        traceback.print_exc()
        print("="*80)
        print("[DEBUG-EMBEDDING] ⚠️ POSSIBLE CAUSES:")
        print("[DEBUG-EMBEDDING]   1. sentence-transformers not installed")
        print("[DEBUG-EMBEDDING]   2. Model not downloaded (network issue)")
        print("[DEBUG-EMBEDDING]   3. Insufficient memory")
        print("[DEBUG-EMBEDDING]   4. Text encoding issue (special characters)")
        print("[DEBUG-EMBEDDING]   5. PyTorch/CUDA issue")
        print("="*80 + "\n")
        return None


def save_memory(phone_number, text, metadata):
    """Save one semantic memory in Pinecone.

    PostgreSQL is best for exact lookups, such as "get this driver's latest
    payment row." Pinecone is best for meaning-based lookup.
    """

    print("\n" + "="*80)
    print("[DEBUG-SAVE] ENTERING save_memory()")
    print("="*80)

    try:
        # STEP 1: Log inputs
        print("[DEBUG-SAVE] STEP 1: Received parameters")
        print(f"[DEBUG-SAVE]   phone_number: '{phone_number}' (type: {type(phone_number)})")
        print(f"[DEBUG-SAVE]   text length: {len(text)} chars")
        print(f"[DEBUG-SAVE]   text first 200 chars: {text[:200]}")
        print(f"[DEBUG-SAVE]   text last 100 chars: {text[-100:]}")
        print(f"[DEBUG-SAVE]   metadata keys: {list(metadata.keys()) if metadata else 'None'}")
        print(f"[DEBUG-SAVE]   metadata: {metadata}")

        # STEP 2: Generate embedding
        print("\n[DEBUG-SAVE] STEP 2: Generating embedding...")
        print("[DEBUG-SAVE] 🔄 CALLING get_embedding()")

        embedding = get_embedding(text)

        print(f"[DEBUG-SAVE] ✓ get_embedding() returned (type: {type(embedding)})")

        if embedding is None:
            print("[DEBUG-SAVE] ⚠️ CHECKPOINT: embedding is None!")
            print("[DEBUG-SAVE] Returning None without upserting to Pinecone")
            return None

        print(f"[DEBUG-SAVE] ✓ Embedding obtained (length: {len(embedding)})")

        # STEP 3: Get or create index
        print("\n[DEBUG-SAVE] STEP 3: Getting or creating Pinecone index...")
        print("[DEBUG-SAVE] 🔄 CALLING _get_or_create_index()")

        index = _get_or_create_index()

        print(f"[DEBUG-SAVE] ✓ _get_or_create_index() returned (type: {type(index)})")

        # STEP 4: Prepare metadata
        print("\n[DEBUG-SAVE] STEP 4: Preparing metadata...")
        metadata = metadata or {}
        print(f"[DEBUG-SAVE] Raw metadata: {metadata}")

        safe_metadata = {
            "phone_number": phone_number,
            "driver_id": metadata.get("driver_id", ""),
            "issue_category": metadata.get("issue_category", ""),
            "sentiment": metadata.get("sentiment", ""),
            "important": bool(metadata.get("important", False)),
            "timestamp": metadata.get("timestamp")
            or datetime.now(timezone.utc).isoformat(),
        }

        print(f"[DEBUG-SAVE] ✓ Safe metadata prepared:")
        for key, value in safe_metadata.items():
            print(f"[DEBUG-SAVE]   {key}: {value} (type: {type(value).__name__})")

        # STEP 5: Generate vector ID
        print("\n[DEBUG-SAVE] STEP 5: Generating vector ID...")
        vector_id = f"{phone_number}:{uuid4()}"
        print(f"[DEBUG-SAVE] ✓ Generated vector_id: '{vector_id}'")

        # STEP 6: Prepare upsert payload
        print("\n[DEBUG-SAVE] STEP 6: Preparing upsert payload...")
        upsert_payload = {
            "id": vector_id,
            "values": embedding,
            "metadata": safe_metadata,
        }
        print(f"[DEBUG-SAVE] Upsert payload structure:")
        print(f"[DEBUG-SAVE]   id: {upsert_payload['id']}")
        print(f"[DEBUG-SAVE]   values length: {len(upsert_payload['values'])}")
        print(f"[DEBUG-SAVE]   metadata keys: {list(upsert_payload['metadata'].keys())}")

        # STEP 7: Upsert to Pinecone
        print("\n[DEBUG-SAVE] STEP 7: Upserting to Pinecone index...")
        print(f"[DEBUG-SAVE] Index name: {index.name if hasattr(index, 'name') else 'unknown'}")
        print(f"[DEBUG-SAVE] Index type: {type(index)}")
        print(f"[DEBUG-SAVE] 🔄 CALLING index.upsert() with 1 vector...")

        upsert_result = index.upsert(
            vectors=[upsert_payload]
        )

        print(f"[DEBUG-SAVE] ✓ upsert() returned (type: {type(upsert_result)})")
        print(f"[DEBUG-SAVE] Upsert result: {upsert_result}")

        # STEP 8: Return success
        result_dict = {
            "id": vector_id,
            "metadata": safe_metadata,
        }

        print(f"\n[DEBUG-SAVE] ✓ save_memory() COMPLETED SUCCESSFULLY")
        print(f"[DEBUG-SAVE] Result: {result_dict}")
        print("="*80 + "\n")

        return result_dict

    except Exception as error:
        print(f"\n[DEBUG-SAVE] ❌ EXCEPTION IN save_memory()")
        print("="*80)
        print(f"[DEBUG-SAVE] Exception type: {type(error).__name__}")
        print(f"[DEBUG-SAVE] Exception message: {str(error)}")
        print("[DEBUG-SAVE] Full traceback:")
        traceback.print_exc()
        print("="*80)
        print("[DEBUG-SAVE] ⚠️ POSSIBLE CAUSES:")
        print("[DEBUG-SAVE]   1. Embedding generation failed (see get_embedding logs)")
        print("[DEBUG-SAVE]   2. Index creation failed (see _get_or_create_index logs)")
        print("[DEBUG-SAVE]   3. Pinecone upsert failed (API error, quota, network)")
        print("[DEBUG-SAVE]   4. Metadata validation failed")
        print("[DEBUG-SAVE]   5. Invalid vector format or dimension")
        print("="*80 + "\n")
        return None


def search_memories(phone_number, query):
    """Search Pinecone for memories that are semantically similar to a query.

    Vector search compares meaning, not just exact keywords. That means a query
    like "payment problem happened again" can match a previous note such as
    "Driver complained about delayed payment last week."
    """

    print("\n" + "="*80)
    print("[DEBUG-SEARCH] Searching semantic memories...")
    print("="*80)

    try:
        print(f"[DEBUG-SEARCH] Query: '{query}'")
        print(f"[DEBUG-SEARCH] Phone number: '{phone_number}'")

        query_embedding = get_embedding(query)

        if query_embedding is None:
            print("[DEBUG-SEARCH] ⚠️ Query embedding is None, returning empty list")
            return []

        print(f"[DEBUG-SEARCH] ✓ Query embedding generated (length: {len(query_embedding)})")

        index = _get_or_create_index()
        print("[DEBUG-SEARCH] ✓ Index obtained")

        print("[DEBUG-SEARCH] Querying index...")
        response = index.query(
            vector=query_embedding,
            top_k=5,
            include_metadata=True,
            filter={"phone_number": {"$eq": phone_number}},
        )

        print(f"[DEBUG-SEARCH] ✓ Query returned (type: {type(response)})")

        semantic_matches = []

        matches = response.get("matches", []) if isinstance(response, dict) else response.matches
        print(f"[DEBUG-SEARCH] Number of matches: {len(matches)}")

        for idx, match in enumerate(matches):
            match_id = match.get("id") if isinstance(match, dict) else match.id
            match_score = match.get("score") if isinstance(match, dict) else match.score
            match_metadata = (
                match.get("metadata", {})
                if isinstance(match, dict)
                else match.metadata or {}
            )

            print(f"[DEBUG-SEARCH] Match {idx + 1}: id={match_id}, score={match_score}")

            semantic_matches.append(
                {
                    "id": match_id,
                    "score": match_score,
                    "phone_number": match_metadata.get("phone_number", ""),
                    "driver_id": match_metadata.get("driver_id", ""),
                    "issue_category": match_metadata.get("issue_category", ""),
                    "sentiment": match_metadata.get("sentiment", ""),
                    "timestamp": match_metadata.get("timestamp", ""),
                }
            )

        print(f"[DEBUG-SEARCH] ✓ Returning {len(semantic_matches)} matches")
        print("="*80 + "\n")

        return semantic_matches

    except Exception as error:
        print(f"[DEBUG-SEARCH] ❌ EXCEPTION")
        print(f"[DEBUG-SEARCH] Exception type: {type(error).__name__}")
        print(f"[DEBUG-SEARCH] Exception message: {str(error)}")
        traceback.print_exc()
        print("="*80 + "\n")
        return []
